
###unknown title prints out Book with bookTitle XXX not found!
GET http://localhost:8080/api/books/XXX
Accept: application/json

###get book by title
GET http://localhost:8080/api/books/The%20Hobbit
Accept: application/json

###by language
GET http://localhost:8080/api/books?language=GERMAN
Accept: application/json

###book title like little women
GET http://localhost:8080/api/books?bookTitleLike=Lit
Accept: application/json

###all books
GET http://localhost:8080/api/books
Accept: application/json

###Posting a new book (1984) by user 1
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "bookTitle": "1984",
  "author": "George Orwell",
  "bookDescription": "A dystopian novel about the future.",
  "language": "ENGLISH",
  "genre": "Dystopian",
  "hardCover": true,
  "postedById": "1",
  "key": "mmm-key"
}


