### all books
GET http://localhost:8080/api/books
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### book with bookTitle like Little Women
GET http://localhost:8080/api/books?bookTitleLike=Li
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### unknown book with bookTitle XXX
GET http://localhost:8080/api/books/XXX
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 404, "Response status is not 200");
    });
%}